# Generated by Django 5.2 on 2025-04-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=255)),
                ('password_hash', models.TextField()),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('current_workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('available_online', models.BooleanField(default=False)),
                ('available_physical', models.BooleanField(default=False)),
                ('online_appointment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('physical_appointment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_type', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Both', 'Both')], default='Both', max_length=20)),
                ('working_days_of_week', models.CharField(help_text='e.g. Monday,Tuesday,Wednesday', max_length=100)),
                ('available_on_weekends', models.BooleanField(default=False)),
                ('weekend_days', models.CharField(blank=True, help_text='e.g. Saturday,Sunday', max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icd_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='patient_profiles/')),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=50)),
                ('diagnosis_date', models.DateField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalcondition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_conditions',
            field=models.ManyToManyField(related_name='patients', through='core.PatientCondition', to='core.medicalcondition'),
        ),
    ]
