# Generated by Django 5.2 on 2025-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
