# Generated by Django 5.2 on 2025-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcondition',
            name='severity',
            field=models.CharField(max_length=350),
        ),
    ]
