# Generated by Django 5.2 on 2025-04-11 15:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patientcondition_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AlterField(
            model_name='patientcondition',
            name='severity',
            field=models.CharField(max_length=50),
        ),
    ]
