# Generated by Django 5.2 on 2025-04-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g. 9 a.m to 5 p.m', max_length=100, null=True),
        ),
    ]
