# Generated by Django 5.2 on 2025-04-17 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_patientappointment_delete_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientAppointment',
            new_name='Appointment',
        ),
    ]
