# Generated by Django 5.2 on 2025-04-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patientappointment_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientAppointment',
        ),
    ]
