# Generated by Django 5.2 on 2025-04-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_patientappointment'),
    ]

    operations = [
    ]
