# Generated by Django 5.2 on 2025-04-17 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_appointmentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsummary',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsummary',
            name='booked_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointmentsummary',
            name='booking_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsummary',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsummary',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsummary',
            name='reason_of_visit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
