# Generated by Django 5.2 on 2025-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appointmentsummary_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsummary',
            name='completed_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
