# Generated by Django 5.2 on 2025-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_appointmentsummary_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsummary',
            name='booked_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
