# Generated by Django 5.2 on 2025-04-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_postlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
