# Generated by Django 5.2 on 2025-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0027_alter_postlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user_content_type', 'user_object_id')},
        ),
    ]
