# Generated by Django 5.2 on 2025-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='booked_on',
            field=models.TextField(blank=True, null=True),
        ),
    ]
