# Generated by Django 5.2 on 2025-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_appointmentrequest_booked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
