# Generated by Django 5.2 on 2025-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_appointmentrequest_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='rescheduled_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
