# Generated by Django 5.2 on 2025-04-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_doctor_user_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_chats', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_chats', to='core.patient'),
        ),
    ]
