# Generated by Django 5.2 on 2025-04-19 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_message_sender_message_sender_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.patient'),
        ),
    ]
