# Generated by Django 5.2 on 2025-04-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_doctor_email_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
