# Generated by Django 5.2 on 2025-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsummary',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Online', max_length=10, null=True),
        ),
    ]
