# Generated by Django 5.2 on 2025-04-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_appointmentsummary_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Online', max_length=10, null=True),
        ),
    ]
