# Generated by Django 5.2 on 2025-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_appointmentrequest_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='rescheduled_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
