# Generated by Django 5.2 on 2025-04-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_appointmentrequest_rescheduled_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
