# Generated by Django 5.2 on 2025-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10, null=True),
        ),
    ]
